version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

    command: uvicorn app.main:app --host 0.0.0.0 --port ${WEB_PORT}
    volumes:
      - .:/app
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    env_file:
      - .env
    restart: always

